mypage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:post_id>/', views.detail, name = 'detail'),
    path('<int:post_id>/results/', views.results, name = 'results'),
    path('<int:post_id>/react/', views.react, name = 'react'),
    #url(r'^api-auth/', include('rest_framework.urls')),
]

polls/models.py
from django.db import models

posts/models.py
import datetime
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User

class Post(models.Model):
    content = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name='user_posts')

    def __str__(self):
        return self.author.username + " " + self.content

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Reaction(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    likes = models.IntegerField(default=0)
    hearts = models.IntegerField(default=0)

    def __str__(self):
        return "likes: " + self.likes + " / heart: " + self.hearts

polls/views.py
from django.shortcuts import render


from django.http import HttpResponse

import datetime
from django.utils import timezone

def index(request):
    dt = timezone.localtime()
    now = dt.strftime("%Y.%m.%d. %H:%M:%S (%A)")
    return HttpResponse("Hello, world! Now is " + now + " (Seoul) [polls]")

posts/views.py
from django.shortcuts import render


from django.http import HttpResponse
from django.http import Http404

from .models import Post
from django.template import loader

from django.shortcuts import render, get_object_or_404

#import datetime
#from django.utils import timezone

def index(request):
    #dt = timezone.localtime()
    #now = dt.strftime("%Y.%m.%d. %H:%M:%S (%A)")

    latest_post_list = Post.objects.order_by('-pub_date')[:5] #show recent 5 posts, ordered by 'pub_date'
    context = {'latest_post_list': latest_post_list}

    return render(request, 'posts/index.html', context)

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    
    return render(request, 'posts/detail.html', {'post': post})

def results(request, post_id):
    response = HttpResponse("You're looking at the results of post %s." % post_id)
    return HttpResponse(response)

def react(request, post_id):
    return HttpResponse("You're reacting on post %s." % post_id)

posts/templates/posts/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
    <h1>{{post.content}}</h1>
    <ul>
        {% for react in post.react_set.all %}
        <li>{{react.likes}}</li>
        <li>{{react.heart}}</li>
    {% endfor %}
    </ul>
</body>
</html>

posts/templates/posts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
        <li><a href="{% url 'posts:detail' post.id %}">{{post.content}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no posts.</p>
{% endif %}

</body>
</html>